services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-movies-go-app
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      MONGODB_URI: mongodb://mongodb:27017
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"